dataset: 'openpose'
joints_to_ign:
    - 1
    - 9
    - 12
data_folder: "data"
output_folder: 'smplx_debug'
prior_folder: 'priors'
model_folder: 'models'
result_folder: 'results'
gender: "neutral"
model_type: 'smplx'
# Flag for using the GPU
use_cuda: True
float_dtype: "float32"
use_joints_conf: True
use_pca: True
use_hands: True
use_face: True
flat_hand_mean: False
# The number of mixture components for the pose prior
num_gaussians: 8
body_prior_type: 'l2'
left_hand_prior_type: l2
right_hand_prior_type: l2
jaw_prior_type: 'l2'
focal_length: 1000
num_pca_comps: 12
# The constant for the robust loss function
rho: 100
interpenetration: False
df_cone_height: 0.0001
# Upper arms and Spine 2
# Neck and jaw
ign_part_pairs: ["9,16", "9,17", "6,16", "6,17", "1,2", "12,22"]
penalize_outside: True
max_collisions: 128
# LBFGS with line search
optim_type: 'lbfgsls'
ftol: 1e-9
gtol: 1e-9
lr: 1.0
# Max number of optimization iterations
maxiters: 30
interactive: True
visualize: True
# Relative change in loss value
body_pose_prior_weights:
   - 7.5
   - 7.5
   - 4.78e0
   - 4.78e0
   - 4.78e0
coll_loss_weights:
   - 0.0
   - 0.0
   - 0.0
   - 0.01
   - 1.0
shape_weights:
   - 150
   - 75
   - 50
   - 20
   - 10
expr_weights:
   - 150
   - 75
   - 50
   - 20
   - 10
hand_pose_prior_weights:
   - 50
   - 50
   - 10
   - 4.78
   - 4.78
jaw_pose_prior_weights:
   # First phase
   - 574,5740,5740
   # Second phase
   - 47.8,478,478
   # Third phase
   - 47.8,478,478
   # Fourth phase
   - 47.8,478,478
   # Fifth phase
   - 47.8,478,478
hand_joints_weights:
   - 0.1
   - 0.2
   - 0.5
   - 1.0
   - 2.0
face_joints_weights:
   - 0.1
   - 0.2
   - 0.5
   - 1.0
   - 2.0
use_face_contour: True
init_joints_idxs:
    [15, 16, 2, 5, 3, 6, 9, 8, 12]
use_vposer: True
vposer_ckpt: "vposer"
num_betas: 200
num_expression_coeffs: 50
regression_prior: PIXIE
use_gender_classifier: True
use_camera_prior: True
summary_folder: "summaries"
summary_steps: 10